#pragma once
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//       LottieGen version:
//           8.1.240821.1+077322fa26
//
//       Command:
//           LottieGen -GenerateColorBindings -Language Cppwinrt -Namespace SuiteInstaller
//           -WinUIVersion 3.0 -InputFile Moon.json
//
//       Input file:
//           Moon.json (10105 bytes created 13:51+02:00 Nov 11 2024)
//
//       LottieGen source:
//           http://aka.ms/Lottie
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#include "Moon.g.h"

namespace winrt::SuiteInstaller
{
// Name:        Switch UI modes 3
// Frame rate:  30 fps
// Frame count: 51
// Duration:    1700.0 mS
// ___________________________________________________________________________
// |      Marker       |      Constant       | Frame |   mS   |   Progress   |
// |___________________|_____________________|_______|________|______________|
// | DarkToLight_Start | M_DarkToLight_Start |     0 |    0.0 | 0.0F         |
// | DarkToLight_End   | M_DarkToLight_End   |    16 |  533.3 | 0.314705878F |
// | LightToDark_Start | M_LightToDark_Start |    23 |  766.7 | 0.451960772F |
// | LightToDark_End   | M_LightToDark_End   |    38 | 1266.7 | 0.746078432F |
// ---------------------------------------------------------------------------
namespace implementation
{
class Moon : public MoonT<Moon>
{
public:
  // Animation duration: 1.700 seconds.
  static constexpr int64_t c_durationTicks{ 17000000L };

  // Marker: DarkToLight_Start.
  static constexpr float M_DarkToLight_Start{ 0.0F };

  // Marker: DarkToLight_End.
  static constexpr float M_DarkToLight_End{ 0.314705878F };

  // Marker: LightToDark_Start.
  static constexpr float M_LightToDark_Start{ 0.451960772F };

  // Marker: LightToDark_End.
  static constexpr float M_LightToDark_End{ 0.746078432F };

  winrt::Microsoft::UI::Xaml::Controls::IAnimatedVisual TryCreateAnimatedVisual(
    winrt::Microsoft::UI::Composition::Compositor const & compositor);

  winrt::Microsoft::UI::Xaml::Controls::IAnimatedVisual TryCreateAnimatedVisual(
    winrt::Microsoft::UI::Composition::Compositor const & compositor,
    winrt::Windows::Foundation::IInspectable &            diagnostics);

  // Gets the number of frames in the animation.
  double FrameCount();

  // Gets the framerate of the animation.
  double Framerate();

  // Gets the duration of the animation.
  winrt::Windows::Foundation::TimeSpan Duration();

  // Converts a zero-based frame number to the corresponding progress value denoting the
  // start of the frame.
  double FrameToProgress(double frameNumber);

  // Returns a map from marker names to corresponding progress values.
  winrt::Windows::Foundation::Collections::IMapView<hstring, double> Markers();

  // Sets the color property with the given name, or does nothing if no such property
  // exists.
  void SetColorProperty(hstring const & propertyName, winrt::Windows::UI::Color value);

  // Sets the scalar property with the given name, or does nothing if no such property
  // exists.
  void SetScalarProperty(hstring const & propertyName, double value);
};
}  // namespace implementation

namespace factory_implementation
{
struct Moon : MoonT<Moon, implementation::Moon>
{
};
}  // namespace factory_implementation
}  // namespace winrt::SuiteInstaller
